image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - staging
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  image: docker/compose:latest
  stage: build
  before_script:
    - cd src
  script:
    - docker-compose build
    - docker-compose push

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com 
  only:
    - branches
  except:
    - master

staging:
  stage: staging
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script: 
    - echo "Deploy"
  environment:
    name: staging
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: production
    url: http://example.example.com
