version: "3.3"

services:
  post_db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
      - prometheus_net
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - back_net
      - prometheus_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - prometheus_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
  prometheus_net:
