version: "3.3"

services:
  post_db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
          - mongodb
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
  
volumes:
  post_db:

networks:
  back_net:
  front_net:
