version: "3.3"

services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      prometheus_net:
        aliases:
          - prometheus
  node_exporter:
    image: prom/node-exporter:v0.18.1
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      prometheus_net:
        aliases:
          - node-exporter
  mongodb_exporter:
    image: forekshub/percona-mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
      back_net:
        aliases:
          - mongodb-exporter
  cloudprober:
    image: ${USERNAME}/cloudprober
    networks:
      prometheus_net:
        aliases:
          - cloudprober-exporter

volumes:
  prometheus_data:

networks:
  prometheus_net:
