version: "3.3"

services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      prometheus_net:
        aliases:
          - prometheus
  node_exporter:
    image: prom/node-exporter:v0.18.1
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      prometheus_net:
        aliases:
          - node-exporter
  mongodb_exporter:
    image: forekshub/percona-mongodb-exporter:latest
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    networks:
      prometheus_net:
        aliases:
          - mongodb-exporter
  cloudprober:
    image: ${USERNAME}/cloudprober
    networks:
      prometheus_net:
        aliases:
          - cloudprober-exporter
  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      prometheus_net:
        aliases:
          - cadvisor
  grafana:
    image: ${USERNAME}/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      prometheus_net:
        aliases:
          - grafana
  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      prometheus_net:
        aliases:
          - alertmanager
  influxdb:
    image: influxdb:1.7.9
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    networks:
      prometheus_net:
        aliases:
          - influxdb
  telegraf:
    image: ${USERNAME}/telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
      - 9273:9273
    networks:
      prometheus_net:
        aliases:
          - telegraf


volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:

networks:
  prometheus_net:
