version: '3.3'

services:
  post_db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    volumes:
      - ui:/app
    command: ["puma","--debug","-w","2"]
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    volumes:
      - post:/app
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    volumes:
      - comment:/app
    command: ["puma","--debug","-w","2"]

volumes:
  post_db:
  ui:
  post:
  comment:
